# Generated by Django 6.0.6 on 2026-08-08 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('APPLICATION', 'Application'), ('ERROR', 'Error'), ('AI', 'AI Event'), ('USER', 'User Action'), ('ADMIN', 'Admin Action'), ('RETRY', 'Retry'), ('SECURITY', 'Security')], max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('WARNING', 'Warning')], default='SUCCESS', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='audit_logs__event_t_2f2dc3_idx'), models.Index(fields=['status'], name='audit_logs__status_01c5be_idx'), models.Index(fields=['created_at'], name='audit_logs__created_0fc90a_idx'), models.Index(fields=['user'], name='audit_logs__user_id_a5e0ec_idx')],
            },
        ),
    ]
