# Generated by Django 6.0.6 on 2026-07-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
    ]
