# Generated by Django 6.0.6 on 2026-07-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
