# Generated by Django 6.0.6 on 2026-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminauditlog'),
        ('applications', '0006_notificationlog'),
        ('jobs', '0003_alter_job_location_alter_job_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job')},
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='application_candida_6c9704_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='application_job_id_2b6ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['ats_score'], name='application_ats_sco_931d81_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='application_applied_06e426_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient'], name='application_recipie_515f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='application_status_0375ca_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='application_created_21a9f0_idx'),
        ),
    ]
