# Generated by Django 6.0.6 on 2026-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20),
        ),
    ]
