# Generated by Django 6.0.6 on 2026-07-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_aiinterviewsession_aiquestion_aianswer_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='transcript',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
