# Generated by Django 6.0.6 on 2026-08-01 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_aiinterviewsession_transcript'),
        ('jobs', '0004_job_jobs_job_employe_da1c9a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Introduction', 'Introduction'), ('Experience', 'Experience'), ('Skills', 'Skills'), ('Availability', 'Availability'), ('Salary', 'Salary')], max_length=30)),
                ('question', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobQuestionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_mappings', to='jobs.job')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.aiquestiontemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
