# Generated by Django 6.0.6 on 2026-08-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_aiquestiontemplate_jobquestionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='last_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='manually_stopped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='max_questions',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='aiinterviewsession',
            name='timeout_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
