# Generated by Django 6.0.6 on 2026-08-03 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_aiinterviewsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnswerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_answer', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_annotation', models.TextField(blank=True, null=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('completeness_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('keyword_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.aiquestiontemplate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='applications.aiinterviewsession')),
            ],
        ),
    ]
