# Generated by Django 6.0.6 on 2026-08-04 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminauditlog'),
        ('applications', '0013_aianswerevaluation'),
        ('jobs', '0004_job_jobs_job_employe_da1c9a_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='accounts.employer')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='jobs.job')),
            ],
            options={
                'ordering': ['available_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_by', models.CharField(default='AI Scheduler', max_length=100)),
                ('confirmation_status', models.BooleanField(default=False)),
                ('interview_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='applications.application')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.availabilityslot')),
            ],
        ),
    ]
