# Generated by Django 6.0.6 on 2026-08-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_availabilityslot_interviewschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='reminder_1hr_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='reminder_24_sent',
            field=models.BooleanField(default=False),
        ),
    ]
