# Generated by Django 6.0.6 on 2026-08-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
