# Generated by Django 6.0.6 on 2026-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_paymenttransaction_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='Optional date/time until which access is allowed after subscription expiry.', null=True),
        ),
    ]
