# Generated by Django 6.0.6 on 2026-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_usersubscription_grace_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='candidate_access_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 means no candidate access unless unlimited_candidate_access is enabled.'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='unlimited_candidate_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, help_text='Optional date/time until which paid access is allowed after subscription expiry.', null=True),
        ),
    ]
