# Generated by Django 6.0.6 on 2026-07-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_adminauditlog'),
        ('jobs', '0003_alter_job_location_alter_job_title'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer'], name='jobs_job_employe_da1c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_job_status_7d017a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['featured'], name='jobs_job_feature_034fc6_idx'),
        ),
    ]
