# Generated by Django 6.0.6 on 2026-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_candidate_education_candidate_expected_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
